# Generated by Django 6.0.1 on 2026-03-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropdrop', '0004_order_address_order_city_order_name_order_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Out for Delivered', 'Out for Delivered'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
