# Generated by Django 6.0.1 on 2026-03-31 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropdrop', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quality',
            field=models.CharField(choices=[('premium', 'Premium'), ('standard', 'Standard'), ('low', 'Low')], default='standard', max_length=20),
        ),
    ]
